[package]
name = "biliroaming-rust-server-installer"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.89"
serde = {version = "1.0.147",features = ["derive"]}
reqwest = {version = "0.11.13",features = ["socks","brotli","gzip","deflate","blocking"]}
dotenv = "0.15.0"